export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS control_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    automation_mode TEXT NOT NULL DEFAULT 'paused',
    timezone TEXT NOT NULL DEFAULT 'Asia/Karachi',
    schedule_hour INTEGER NOT NULL DEFAULT 21,
    lead_target INTEGER NOT NULL DEFAULT 10,
    email_cap INTEGER NOT NULL DEFAULT 10,
    application_cap INTEGER NOT NULL DEFAULT 5,
    followup_days TEXT NOT NULL DEFAULT '3,6,10,15,21,30,45',
    target_markets TEXT NOT NULL DEFAULT 'International, remote-first startup founders and product companies',
    ideal_customer_profile TEXT NOT NULL DEFAULT 'Early-stage founder-led software companies with 1-50 employees, an MVP or live product, and a need for hands-on technical ownership, a founding engineer, technical co-founder, CTO partner, product audit, MVP delivery, stabilization, or fundraising readiness',
    lead_titles TEXT NOT NULL DEFAULT 'Founder, Co-Founder, CEO, CTO, Head of Product, Product Lead',
    wellfound_roles TEXT NOT NULL DEFAULT 'Technical Co-Founder, Co-Founder, Founding Engineer, CTO, Senior Software Engineer, Senior Full-Stack Engineer, Full-Stack Engineer, Backend Engineer, Frontend Engineer, Product Engineer, Software Engineer, Data Scientist',
    wellfound_locations TEXT NOT NULL DEFAULT 'Remote only; use the existing saved Wellfound region set shown as Japan +10; company size 1-10 or 11-50; any salary; any equity; no investment-stage restriction',
    min_compensation TEXT NOT NULL DEFAULT '',
    application_facts TEXT NOT NULL DEFAULT 'Sarmad Irfan; Lahore, Pakistan; remote and international; Technical Partner / Product Engineer; 5+ years of software engineering experience, work authorization, Node.js experience, and WebGL experience confirmed directly by Sarmad on 2026-09-07; React, Next.js, TypeScript, React Native, Expo, Express, PostgreSQL, Supabase, Firebase, Docker, GitHub, CI/CD, cloud deployment, APIs, authentication, RBAC, and system architecture; GitHub https://github.com/sarmad0324; website https://www.sarmadirfan.com/; more than two years of end-to-end technical ownership on TruckWise. Work-authorization country/region, compensation expectations, exact availability, degree completion, and any other unverified answer must not be invented.',
    approval_policy TEXT NOT NULL DEFAULT 'review_first',
    notify_by_email INTEGER NOT NULL DEFAULT 1,
    notification_email TEXT NOT NULL DEFAULT 'sarmad@sarmadirfan.com',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS connection_status (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    channel TEXT NOT NULL,
    status TEXT NOT NULL,
    identity TEXT NOT NULL,
    detail TEXT NOT NULL,
    checked_at TEXT NOT NULL,
    action_url TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS automation_runs (
    id TEXT PRIMARY KEY,
    run_type TEXT NOT NULL,
    trigger_source TEXT NOT NULL,
    status TEXT NOT NULL,
    requested_at TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT,
    requested_by TEXT,
    lead_target INTEGER NOT NULL DEFAULT 0,
    email_cap INTEGER NOT NULL DEFAULT 0,
    application_cap INTEGER NOT NULL DEFAULT 0,
    leads_found INTEGER NOT NULL DEFAULT 0,
    leads_qualified INTEGER NOT NULL DEFAULT 0,
    emails_sent INTEGER NOT NULL DEFAULT 0,
    followups_sent INTEGER NOT NULL DEFAULT 0,
    applications_submitted INTEGER NOT NULL DEFAULT 0,
    replies_detected INTEGER NOT NULL DEFAULT 0,
    summary TEXT,
    blocker TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS leads (
    id TEXT PRIMARY KEY,
    company TEXT NOT NULL,
    contact_name TEXT NOT NULL,
    title TEXT NOT NULL,
    email TEXT,
    source TEXT NOT NULL,
    qualification_score INTEGER,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    last_contact_at TEXT,
    next_followup_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS applications (
    id TEXT PRIMARY KEY,
    company TEXT NOT NULL,
    role TEXT NOT NULL,
    source_url TEXT,
    fit_score INTEGER,
    status TEXT NOT NULL,
    applied_at TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS replies (
    id TEXT PRIMARY KEY,
    channel TEXT NOT NULL,
    sender_name TEXT NOT NULL,
    sender_address TEXT,
    subject TEXT NOT NULL,
    sentiment TEXT NOT NULL,
    received_at TEXT NOT NULL,
    status TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS activity_events (
    id TEXT PRIMARY KEY,
    run_id TEXT,
    event_type TEXT NOT NULL,
    label TEXT NOT NULL,
    detail TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    FOREIGN KEY (run_id) REFERENCES automation_runs(id)
  )`,
  `CREATE TABLE IF NOT EXISTS approval_items (
    id TEXT PRIMARY KEY,
    item_type TEXT NOT NULL,
    related_id TEXT NOT NULL,
    company TEXT NOT NULL,
    contact_name TEXT,
    target TEXT,
    subject TEXT NOT NULL,
    payload_preview TEXT NOT NULL,
    source_url TEXT,
    readiness TEXT NOT NULL DEFAULT 'blocked',
    blocker TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL,
    decided_at TEXT,
    decided_by TEXT,
    run_id TEXT,
    FOREIGN KEY (run_id) REFERENCES automation_runs(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_automation_runs_requested_at ON automation_runs(requested_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_automation_runs_queue ON automation_runs(status, requested_at)`,
  `CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_applications_created_at ON applications(created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_replies_received_at ON replies(received_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_activity_events_occurred_at ON activity_events(occurred_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_approval_items_queue ON approval_items(status, readiness, created_at)`,
];

export const defaultApprovalItems = [
  {
    id: 'approval-email-20260901-001', itemType: 'email', relatedId: 'lead-20260901-001', company: 'telmi', contactName: 'Véronique Trang', target: 'vero@telmi.io',
    subject: 'Telmi’s prototype-to-production step', readiness: 'ready', blocker: '',
    preview: 'Personalized founder email about taking Telmi from a working prototype and pilot schools to a stable Next.js/Supabase production product. Includes Sarmad’s relevant product-ownership experience, a low-friction technical-risk review offer, and a simple opt-out.',
  },
  {
    id: 'approval-email-20260901-002', itemType: 'email', relatedId: 'lead-20260901-002', company: 'Aistetic', contactName: 'Duncan McKay', target: 'duncan@aistetic.com',
    subject: 'React Native ownership for ListingFlow', readiness: 'ready', blocker: '',
    preview: 'Personalized founder email about Aistetic’s self-serve ListingFlow journey and React Native mobile build, positioning Sarmad for a low-risk first milestone.',
  },
  {
    id: 'approval-email-20260901-003', itemType: 'email', relatedId: 'lead-20260901-003', company: 'Lamina', contactName: 'Deep Banerjee', target: 'deep.banerjee@getmason.io',
    subject: 'Product engineering for Lamina’s canvas', readiness: 'ready', blocker: '',
    preview: 'Personalized founder email about Lamina’s collaborative canvas, asynchronous generation jobs, integrations, and architecture/delivery risk.',
  },
  {
    id: 'approval-email-20260901-004', itemType: 'email', relatedId: 'lead-20260901-004', company: 'CleverApply', contactName: 'Joseph Pedicini', target: '',
    subject: 'CleverApply’s Bubble-to-modern-stack migration', readiness: 'blocked', blocker: 'A verified business email address is still required.',
    preview: 'Personalized founder email focused on Bubble-to-React/Node/PostgreSQL migration risks and a concise migration checklist.',
  },
  {
    id: 'approval-email-20260901-005', itemType: 'email', relatedId: 'lead-20260901-005', company: 'Coda', contactName: 'Yuvika Diwan', target: 'careers@coda-engine.ai',
    subject: 'Technical ownership for Coda’s founding build', readiness: 'ready', blocker: '',
    preview: 'Personalized founder email connecting Coda’s physical-mobility reliability needs with Sarmad’s logistics product ownership.',
  },
  {
    id: 'approval-email-20260901-006', itemType: 'email', relatedId: 'lead-20260901-006', company: 'Open Rewards', contactName: 'Sophia Zheng', target: 'sophia@bludot.io',
    subject: 'Product ownership across Open Rewards', readiness: 'ready', blocker: '',
    preview: 'Personalized founder email offering hands-on product ownership across React/Next.js, mobile, APIs, payments, launches, and stabilization. Includes a simple opt-out.',
  },
  {
    id: 'approval-email-20260901-007', itemType: 'email', relatedId: 'lead-20260901-007', company: 'iGrow', contactName: 'Pallavi Bhatt', target: 'teams@i-grow.co',
    subject: 'Technical ownership before iGrow’s next raise', readiness: 'ready', blocker: '',
    preview: 'Personalized founder email offering a compact technical-readiness framework for iGrow’s architecture and fundraising conversations.',
  },
  {
    id: 'approval-email-20260901-008', itemType: 'email', relatedId: 'lead-20260901-008', company: 'Floom', contactName: 'Federico De Ponte', target: 'hello@fedeponte.com',
    subject: 'From single Docker to managed cloud', readiness: 'ready', blocker: '',
    preview: 'Personalized founder email about tenant isolation, deployment reliability, authentication, observability, CLI/SDK, and a managed-cloud transition.',
  },
  {
    id: 'approval-email-20260901-009', itemType: 'email', relatedId: 'lead-20260901-009', company: 'Class8', contactName: 'Chris Atkinson', target: 'chris@class8.com',
    subject: 'AI-first product delivery for trucking fleets', readiness: 'ready', blocker: '',
    preview: 'Personalized founder email connecting Class8’s trucking platform to Sarmad’s long-term logistics engineering and AI workflow experience.',
  },
  {
    id: 'approval-email-20260901-010', itemType: 'email', relatedId: 'lead-20260901-010', company: 'Mura', contactName: 'Ryan G. Smith', target: 'ryan@mura.co',
    subject: 'Founding product engineering for Mura', readiness: 'ready', blocker: '',
    preview: 'Personalized founder email about reliable AI billing automation, operational workflows, systems design, and founding-level product decisions.',
  },
  ...[
    ['001', 'telmi', 'Full Stack Engineer (Next.js / Supabase / AI-Native Workflow)', 'https://wellfound.com/jobs/4079967-full-stack-engineer-next-js-supabase-ai-native-workflow', 'GitHub URL, end-to-end product example, availability, and work authorization must be confirmed.'],
    ['002', 'Aistetic', 'Founding Product Engineer (React Native)', 'https://wellfound.com/jobs/4491678-founding-product-engineer-react-native', 'Availability, work authorization, GitHub or shipped-app evidence, and exact experience must be confirmed.'],
    ['003', 'Lamina', 'Frontend Software Engineer — Remote (global)', 'https://wellfound.com/jobs/4589345-frontend-software-engineer-remote-global-full-time-2-5-years', 'Work authorization, availability, exact experience, and any node-editor/WebGL answer must be confirmed.'],
    ['004', 'Bespoke', 'Full Stack Product Engineer', 'https://wellfound.com/jobs/4461854-full-stack-product-engineer', 'Eastern Time availability, work authorization, exact experience, and compensation expectations must be confirmed.'],
    ['005', 'Lesto Labs', 'Senior Full-Stack Product Engineer — React Native, Node.js, Next.js', 'https://wellfound.com/jobs/4546260-senior-full-stack-product-engineer-react-native-node-js-next-js', 'A public work sample, exact experience, availability, work authorization, and compensation expectations must be confirmed.'],
  ].map(([suffix, company, role, sourceUrl]) => ({
    id: `approval-application-20260901-${suffix}`,
    itemType: 'application', relatedId: `app-20260901-${suffix}`, company, contactName: '', target: 'Wellfound',
    subject: role, sourceUrl, readiness: 'ready', blocker: '',
    preview: `Truthful personalized Wellfound application for ${company}, using Sarmad’s confirmed 5+ years, work authorization, Node.js/WebGL experience where relevant, GitHub profile, portfolio, and TruckWise ownership example. The worker must pause this item if the live form introduces a required fact that is not in the verified profile.`,
  })),
];

export const defaultConnections = [
  {
    id: 'gmail',
    name: 'Gmail',
    channel: 'Outbound and reply detection',
    status: 'connected',
    identity: 'Sarmad Irfan · sarmad@sarmadirfan.com',
    detail: 'Direct Gmail connector verified. Sending remains governed by the saved caps and run policy.',
    actionUrl: 'https://mail.google.com/',
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    channel: 'Lead and application register',
    status: 'connected',
    identity: 'Sarmad Company OS — Live Register',
    detail: 'Native register with Dashboard, Leads, Outreach, Applications, Replies, Settings, and Lists tabs.',
    actionUrl: 'https://docs.google.com/spreadsheets/d/1k5jx9vr5rTk0c1Ly0K-bB40zmV9dH3pPKnAoqr-KA7M/edit',
  },
  {
    id: 'wellfound',
    name: 'Wellfound',
    channel: 'Job discovery and applications',
    status: 'connected',
    identity: 'Sarmad Irfan · signed-in browser session',
    detail: 'The signed-in browser session is available. Submissions require completed role filters and truthful application facts.',
    actionUrl: 'https://wellfound.com/jobs',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    channel: 'Lead research and relationship context',
    status: 'connected',
    identity: 'Sarmad Irfan · signed-in browser session',
    detail: 'The signed-in browser session is available for research. No autonomous messaging or profile changes are enabled.',
    actionUrl: 'https://www.linkedin.com/feed/',
  },
  {
    id: 'apollo',
    name: 'Apollo',
    channel: 'Lead discovery and enrichment',
    status: 'connected',
    identity: 'Sarmad Irfan · sarmad@sarmadirfan.com',
    detail: 'Direct connector verified for discovery and enrichment. Credit balance is checked by the execution agent before a run.',
    actionUrl: 'https://app.apollo.io/',
  },
];
